### ISSUE TITLE
Loading speed of contest page is slow

### ISSUE THREAD

**Issue by nickelcheng** [nthuoj/NTHUOJ_web#77]
@bruce3557 found the loading speed of contest page is slow.
Any possible solution to solve this?
(Like loading page by ajax and show each section separately)

**Comment by nickelcheng** [comment]
@Changron does it fixed?

**Comment by Changron** [comment]
I think not
I think the detail of the contest should be dynamically loaded. Load only when user wants to know. I think that would be faster

**Comment by nickelcheng** [comment]
Please fix it in future PR
