### ISSUE TITLE
Unify coding style

### ISSUE THREAD

**Issue by nickelcheng** [nthuoj/NTHUOJ_web#78]
use linter or [Travis CI](https://travis-ci.org/getting_started)

**Comment by hydai** [comment]
I write an note for Travis CI.
http://hydai.logdown.com/snippets/258417-travis-ci-automated-testing-your-project

It will test coding style and unit test automatically when contributors send PR.
Reviewer can find some coding style issues before reviewing the detail code.

**Comment by henryyang42** [comment]
Thanks for your hard work!

**Comment by nickelcheng** [comment]
Thanks a lot!
